//
// Created by disojivm on 5/7/19.
//

#ifndef ARQUI2_PROYECTO2_MEM_OPS_H
#define ARQUI2_PROYECTO2_MEM_OPS_H

#endif //ARQUI2_PROYECTO2_MEM_OPS_H

#define DATA_MEMORY_SIZE 1048576
#define INSTRUCTION_MEMORY_SIZE 2048

#define REGISTER_SIZE 12
#define REGISTER_BANK_SIZE 8